FROM nginx:1.14

RUN apt-get update
RUN apt-get install -y vim

# Copy the config files
COPY ./config/nginx.conf /etc/nginx/nginx.conf
COPY ./config/site-config /etc/nginx/site-config

VOLUME ["/etc/nginx/conf.d", "/etc/nginx/sites-available", "/var/code"]
